### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by yzinets** [j4321/MyNotes#3]
![image](https://user-images.githubusercontent.com/17050536/27360945-b9666816-5613-11e7-9204-1a0f1f297724.png)
As you can see, icon is displayed incorrectly

**Comment by j4321** [comment]
I am aware of this issue, but this is a Tktray issue and I don't have the skills to look into it. Since Tktray  has not been updated in years, I doubt that reporting the bug upstream will be useful. I will try to find a more active library, but for now, just try refreshing/restarting the panel, usually it corrects the display issue.
